from django.urls import path
from .views import DocenteList, DocenteDetail, NivelDocenteList, NivelDocenteDetail, PagoList, PagoDetail, CursoList, CursoDetail, CursoDocenteList, CursoDocenteDetail, CarreraList, CarreraDetail, ModuloList, ModuloDetail, AdministrativoList, AdministrativoDetail, GrupoList, GrupoDetail, GrupoModuloList, GrupoModuloDetail, HorasClaseList, HorasClaseDetail, HorasClaseGrupoModuloList, HorasClaseGrupoModuloDetail, AlumnoList, AlumnoDetail, SesionList, SesionDetail, RecursoList, RecursoDetail

urlpatterns = [
    path('docentes/', DocenteList.as_view(), name='docente-list'),
    path('docentes/<int:pk>/', DocenteDetail.as_view(), name='docente-detail'),
    path('niveles-docentes/', NivelDocenteList.as_view(), name='nivel-docente-list'),
    path('niveles-docentes/<int:pk>/', NivelDocenteDetail.as_view(), name='nivel-docente-detail'),
    path('pagos/', PagoList.as_view(), name='pago-list'),
    path('pagos/<int:pk>/', PagoDetail.as_view(), name='pago-detail'),
    path('cursos/', CursoList.as_view(), name='curso-list'),
    path('cursos/<int:pk>/', CursoDetail.as_view(), name='curso-detail'),
    path('curso-docentes/', CursoDocenteList.as_view(), name='curso-docente-list'),
    path('curso-docentes/<int:pk>/', CursoDocenteDetail.as_view(), name='curso-docente-detail'),
    path('carreras/', CarreraList.as_view(), name='carrera-list'),
    path('carreras/<int:pk>/', CarreraDetail.as_view(), name='carrera-detail'),
    path('modulos/', ModuloList.as_view(), name='modulo-list'),
    path('modulos/<int:pk>/', ModuloDetail.as_view(), name='modulo-detail'),
    path('administrativos/', AdministrativoList.as_view(), name='administrativo-list'),
    path('administrativos/<int:pk>/', AdministrativoDetail.as_view(), name='administrativo-detail'),
    path('grupos/', GrupoList.as_view(), name='grupo-list'),
    path('grupos/<int:pk>/', GrupoDetail.as_view(), name='grupo-detail'),
    path('grupo-modulos/', GrupoModuloList.as_view(), name='grupo-modulo-list'),
    path('grupo-modulos/<int:pk>/', GrupoModuloDetail.as_view(), name='grupo-modulo-detail'),
    path('horas-clase/', HorasClaseList.as_view(), name='horas-clase-list'),
    path('horas-clase/<int:pk>/', HorasClaseDetail.as_view(), name='horas-clase-detail'),
    path('horas-clase-grupo-modulos/', HorasClaseGrupoModuloList.as_view(), name='horas-clase-grupo-modulo-list'),
    path('horas-clase-grupo-modulos/<int:pk>/', HorasClaseGrupoModuloDetail.as_view(), name='horas-clase-grupo-modulo-detail'),
    path('alumnos/', AlumnoList.as_view(), name='alumno-list'),
    path('alumnos/<int:pk>/', AlumnoDetail.as_view(), name='alumno-detail'),
    path('sesiones/', SesionList.as_view(), name='sesion-list'),
    path('sesiones/<int:pk>/', SesionDetail.as_view(), name='sesion-detail'),
    path('recursos/', RecursoList.as_view(), name='recurso-list'),
    path('recursos/<int:pk>/', RecursoDetail.as_view(), name='recurso-detail'),
]
