# Generated by Django 5.1.2 on 2024-11-02 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('claveAdministrativo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('primerApellido', models.CharField(max_length=50)),
                ('segundoApellido', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('telefonoCelular', models.CharField(max_length=13)),
                ('correoElectronico', models.EmailField(max_length=250)),
                ('titulo', models.CharField(choices=[('LICENCIADO/A', 'Licenciado/a'), ('INGENIERO/A', 'Ingeniero/a'), ('MAESTRO/A', 'Maestro/a')], max_length=20)),
                ('genero', models.CharField(choices=[('HOMBRE', 'Hombre'), ('MUJER', 'Mujer')], max_length=10)),
                ('estatus', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('matricula', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('primerApellido', models.CharField(max_length=50)),
                ('segundoApellido', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('curp', models.CharField(max_length=18)),
                ('fechaNacimiento', models.DateField()),
                ('domicilio', models.TextField()),
                ('telefonoDomicilio', models.CharField(blank=True, max_length=13, null=True)),
                ('telefonoCelular', models.CharField(max_length=13)),
                ('correoElectronico', models.EmailField(max_length=250)),
                ('ciudadNacimiento', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[('HOMBRE', 'Hombre'), ('MUJER', 'Mujer')], max_length=10)),
                ('estatus', models.BooleanField()),
                ('turno', models.CharField(choices=[('MATUTINO', 'Matutino'), ('VESPERTINO', 'Vespertino')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id_carrera', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('hora', models.IntegerField()),
                ('modalidad', models.CharField(choices=[('VIRTUAL', 'Virtual'), ('PRESENCIAL', 'Presencial'), ('HIBRIDA', 'Híbrida')], max_length=10)),
                ('rol', models.CharField(choices=[('IMPARTIDO', 'Impartido'), ('RECIBIDO', 'Recibido')], max_length=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('claveDocente', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('primerApellido', models.CharField(max_length=50)),
                ('segundoApellido', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('rfc', models.CharField(max_length=13)),
                ('curp', models.CharField(max_length=18)),
                ('fechaNacimiento', models.DateField()),
                ('domicilio', models.TextField()),
                ('telefonoDomicilio', models.CharField(blank=True, max_length=13, null=True)),
                ('telefonoCelular', models.CharField(max_length=13)),
                ('correoElectronico', models.EmailField(max_length=250)),
                ('ciudadNacimiento', models.CharField(max_length=100)),
                ('nivelEstudios', models.CharField(choices=[('PROFESIONAL TECNICO BACHILLER', 'Profesional Técnico Bachiller'), ('LICENCIATURA TITULADA', 'Licenciatura Titulada'), ('PASANTE DE LICENCIATURA', 'Pasante de Licenciatura'), ('MAESTRIA TITULADA', 'Maestría Titulada'), ('BACHILLERATO', 'Bachillerato')], max_length=30)),
                ('genero', models.CharField(choices=[('HOMBRE', 'Hombre'), ('MUJER', 'Mujer')], max_length=10)),
                ('areasFormacion', models.CharField(max_length=100)),
                ('fechaIngresoConalep', models.DateField()),
                ('nivelDocente', models.CharField(choices=[('INSTRUCTO C', 'Instructo C'), ('TECNICO CB I', 'Técnico CB I'), ('TECNICO CB II', 'Técnico CB II'), ('TECNICO INSTRUCTOR A', 'Técnico Instructor A')], max_length=20)),
                ('estatus', models.BooleanField()),
                ('turno', models.CharField(choices=[('MATUTINO', 'Matutino'), ('VESPERTINO', 'Vespertino')], max_length=10)),
                ('horasFrenteGrupo', models.IntegerField()),
                ('edad', models.IntegerField()),
                ('horasBasificadas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HorasClase',
            fields=[
                ('id_horasClase', models.AutoField(primary_key=True, serialize=False)),
                ('horaInicio', models.CharField(max_length=25)),
                ('horaFin', models.CharField(max_length=25)),
                ('cantidadHoras', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id_modulo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('horas', models.IntegerField()),
                ('creditos', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('abrCarrera', models.CharField(choices=[('CONA', 'Cona'), ('ENFE', 'Enfe'), ('CDIA', 'Cdia'), ('INFO', 'Info'), ('N/A', 'N/A')], default='N/A', max_length=4)),
                ('carrera', models.CharField(choices=[('CONTABILIDAD', 'Contabilidad'), ('ENFERMERIA', 'Enfermería'), ('CIENCIA DE DATOS E INTELIGENCIA ARTIFICIAL', 'Ciencia de Datos e Inteligencia Artificial'), ('INFORMATICA', 'Informática'), ('N/A', 'N/A')], default='N/A', max_length=100)),
                ('nucleoFormacion', models.CharField(choices=[('DISCIPLINAR BASICA', 'Disciplinar Básica'), ('PROFESIONAL', 'Profesional'), ('TRAYECTO TECNICO', 'Trayecto Técnico')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NivelDocente',
            fields=[
                ('nivelDocente', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sueldoBase', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CursoDocente',
            fields=[
                ('id_curso_docente', models.AutoField(primary_key=True, serialize=False)),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConalepApi.curso')),
                ('claveDocente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConalepApi.docente')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id_grupo', models.AutoField(primary_key=True, serialize=False)),
                ('abrCarrera', models.CharField(choices=[('CONA', 'Cona'), ('ENFE', 'Enfe'), ('CDIA', 'Cdia'), ('INFO', 'Info')], max_length=4)),
                ('claveAdministrativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConalepApi.administrativo')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoModulo',
            fields=[
                ('id_grupo_modulo', models.AutoField(primary_key=True, serialize=False)),
                ('id_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConalepApi.grupo')),
                ('id_modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConalepApi.modulo')),
            ],
        ),
        migrations.CreateModel(
            name='HorasClaseGrupoModulo',
            fields=[
                ('id_horasClase_grupoModulo', models.AutoField(primary_key=True, serialize=False)),
                ('diaSemana', models.CharField(choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miércoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes')], max_length=10)),
                ('id_grupo_modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConalepApi.grupomodulo')),
                ('id_horasClase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConalepApi.horasclase')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('frecuenciaPago', models.CharField(choices=[('QUINCENAL', 'Quincenal'), ('SEMESTRAL', 'Semestral')], max_length=10)),
                ('totalPago', models.IntegerField()),
                ('claveDocente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConalepApi.docente')),
                ('nivelDocente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConalepApi.niveldocente')),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id_recurso', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('url', models.TextField()),
                ('tipo', models.CharField(choices=[('VIDEO', 'Video'), ('PDF', 'PDF'), ('IMAGEN', 'Imagen')], max_length=10)),
                ('fecha_subida', models.DateTimeField()),
                ('claveDocente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConalepApi.docente')),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id_sesion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('duracion', models.IntegerField()),
                ('tipo', models.CharField(choices=[('PSICOLOGIA', 'Psicología'), ('MATERIA', 'Materia')], max_length=10)),
                ('modalidad', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('GRUPAL', 'Grupal')], max_length=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], max_length=10)),
                ('claveDocente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConalepApi.docente')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConalepApi.alumno')),
            ],
        ),
    ]
