# Generated by Django 5.1.2 on 2024-11-02 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConalepApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoAlumno',
            fields=[
                ('id_grupo_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('id_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConalepApi.grupo')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConalepApi.alumno')),
            ],
        ),
        migrations.AddField(
            model_name='grupo',
            name='alumnos',
            field=models.ManyToManyField(through='ConalepApi.GrupoAlumno', to='ConalepApi.alumno'),
        ),
    ]
